### ISSUE TITLE
`guard` does not recognize `else`

### ISSUE THREAD

**Issue by doug719** [lexi-lambda/racket-r7rs#15] opened 2021-07-17 12:43 UTC
Some small problems with racket8.1 [cs] with r7rs.  Using Linux Mint 20.

1. (display (apply values '(1 2 3))) gives error
2. else not recognized in guard statement
3. guard does not handle zero divisor

Regards,
Doug

**Comment by lexi-lambda** [comment] 2022-02-19 15:27
1. I don’t believe the behavior of `(display (apply values '(1 2 3)))` is specified in the report, so I do not think raising an error is a bug. Please correct me if I’m wrong about this.

2. I agree that this is a bug and should be fixed.

3. I’m not sure what you mean by this. Could you give an example of a program that you think should behave differently?

**Comment by lexi-lambda** [comment] 2022-02-19 16:04
Actually, I take back what I said about point (2), because as far as I can tell, `guard` *does* recognize `else`:

```scheme
> (guard (condition
          (else 'else))
    (raise #t))
else
```

So I’m going to close all of these as “not a bug”, but do feel free to reopen or open another issue if you have more information.

**Closed as completed by lexi-lambda** 2022-02-19 16:04 UTC
