### ISSUE TITLE
Differences in behaviour to racket

### ISSUE THREAD

**Issue by pmatos** [lexi-lambda/racket-r7rs#14] opened 2020-04-30 10:45 UTC
Unsure this is a bug, but is there a reason why:
```
#lang racket
(+ 2 2)
```
and
```
#lang r7rs
(import (scheme base))
(+ 2 2)
```
The first prints 4 and the second prints nothing when ran with `racket`. Is there a way to enable the print behaviour in `r7rs`?

**Comment by lexi-lambda** [comment] 2020-08-16 18:02
As far as I can tell, R7RS leaves whether or not such values are printed or ignored unspecified. As a general rule, this library avoids doing anything not explicitly mandated by the standard, which is consistent with `#lang r5rs` and `#lang r6rs`, so I’m going to close this as “not a bug.”

**Closed as completed by lexi-lambda** 2020-08-16 18:02 UTC
